### ISSUE TITLE
感谢大佬，我有个关于图像生成captions的疑问

### ISSUE THREAD

**Issue by underworld02** [Shuyu-XJTU/APTM#10]
您之前回复说是直接使用BLIP的预训练版本来生成captions，您具体是用的哪个BLIP的预训练版本？我用BLIP生成出来的captions好像都很简略，得不到穿着颜色之类的细粒度信息。不知道您具体是如何操作的，是否有对BLIP进行生成细粒度信息的微调。

**Comment by Shuyu-XJTU** [comment]
你好。我们生成caption 使用的 BLIP 是集成在imaginAIry中的，具体如链接和截图所示。我们没有微调BLIP。

brycedrennan/imaginAIry: AI imagined images. Pythonic generation of images. (github.com)



-----原始邮件-----
发件人:汐風 ***@***.***>
发送时间:2023-10-24 09:43:29 (星期二)
收件人: Shuyu-XJTU/APTM ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Shuyu-XJTU/APTM] 感谢大佬，我有个关于图像生成captions的疑问 (Issue #10)






您之前回复说是直接使用BLIP的预训练版本来生成captions，您具体是用的哪个BLIP的预训练版本？我用BLIP生成出来的captions好像都很简略，得不到穿着颜色之类的细粒度信息。不知道您具体是如何操作的，是否有对BLIP进行生成细粒度信息的微调。

**Comment by shams2023** [comment]
> 您之前回复说是直接使用BLIP的预训练版本来生成captions，您具体是用的哪个BLIP的预训练版本？我用BLIP生成出来的captions好像都很简略，得不到穿着颜色之类的细粒度信息。不知道您具体是如何操作的，是否有对BLIP进行生成细粒度信息的微调。

请问 这个问题您解决了吗？我也遇到了类似的问题，想向您请教一下解决方案！
