### ISSUE TITLE
请教一下生成caption的prompt

### ISSUE THREAD

**Issue by laiping-lp** [Shuyu-XJTU/APTM#15]
我想请教一下，您文章中使用BLIP对图片生成caption的prompt是怎么设置的？方便告诉一下吗

**Comment by Shuyu-XJTU** [comment]
你好。prompt是CUHK-PEDES和ICFG-PEDES两个数据集的caption。


-----原始邮件-----
发件人:laiping-lp ***@***.***>
发送时间:2024-01-27 10:19:10 (星期六)
收件人: Shuyu-XJTU/APTM ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Shuyu-XJTU/APTM] 请教一下生成caption的prompt (Issue #15)






我想请教一下，您文章中使用BLIP对图片生成caption的prompt是怎么设置的？方便告诉一下吗

**Comment by laiping-lp** [comment]
> 你好。prompt是CUHK-PEDES和ICFG-PEDES两个数据集的caption。
> […](#)
> -----原始邮件----- 发件人:laiping-lp ***@***.***> 发送时间:2024-01-27 10:19:10 (星期六) 收件人: Shuyu-XJTU/APTM ***@***.***> 抄送: Subscribed ***@***.***> 主题: [Shuyu-XJTU/APTM] 请教一下生成caption的prompt (Issue #15) 我想请教一下，您文章中使用BLIP对图片生成caption的prompt是怎么设置的？方便告诉一下吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

这个caption是用来生成图片的吧，我想问的是，生成图片后，对图片重新标注caption所用的prompt是什么

**Comment by shams2023** [comment]
> > 你好。提示是CUHK-PEDES和ICFG-PEDES两个数据集的标题。
> > […](#) 
> > -----原始邮件-----发件人:laiping-lp _**@**_ . _**> 发送时间:2024-01-27 10:19:10 (星期六) 线路: Shuyu-XJTU/APTM _**@**_ . **_> 抄送：已订阅_**@**_。_**> 主题: [Shuyu-XJTU/APTM] 请教一下生成字幕的提示（第[15](https://github.com/Shuyu-XJTU/APTM/issues/15)期） 我想请教一下，您文章中使用BLIP对图片生成字幕的提示是怎么设置的？方便告诉一下吗 — 回复此直接发送电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了该线程。消息 ID：_**@**_。**_>
> 
> 这个caption是用来生成图片的吧，我想问的是，生成图片后，对图片重新标注caption所用的提示是什么

请问你解决这个问题了吗？如何对图像生成caption

**Comment by shams2023** [comment]
> 我想请教一下，你的文章中使用BLIP对图片生成字幕的提示是怎么设置的？方便告诉一下吗？

我希望能和你交流这个方向，谢谢!

**Comment by Shuyu-XJTU** [comment]
我们生成caption 使用的 BLIP 是集成在imaginAIry（https://github.com/brycedrennan/imaginAIry）中的。
![caption](https://github.com/Shuyu-XJTU/APTM/assets/137055752/6c115856-8053-4065-b9cd-69328ed81434)

**Comment by shams2023** [comment]
> 我们生成caption 使用的 BLIP 是集成在imaginAIry [https://github.com/brycedrennan/imaginAIry] 中的。 ![caption](https://private-user-images.githubusercontent.com/137055752/308099653-6c115856-8053-4065-b9cd-69328ed81434.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwODM5NDUsIm5iZiI6MTcwOTA4MzY0NSwicGF0aCI6Ii8xMzcwNTU3NTIvMzA4MDk5NjUzLTZjMTE1ODU2LTgwNTMtNDA2NS1iOWNkLTY5MzI4ZWQ4MTQzNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMTI3MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODhkMzZjMDBmMGFhNTM4MTg3MDBiMmYzZmM0NDQ2NGEzZDlhZDg1NzYzZGEwNDkyMDc3MjU5YzMyODA0NjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c3R3hdmntTk0NYCIWyHGw9o68d0NzdW3H_kp9rMuSrs)

你是针对行人图像来生成对应的文本描述的，但据我所知（只是了解）行人图像普遍分辨率低（即很模糊），那么你使用BLIP（集成的）是否可以很好的对这类图像进行较好的文本描述的生成？
因为我目前自己收集了一些傍晚的行人图像，普遍模糊，相对这些图像进行caption的生成，所以特来向您请教。万分感谢！

**Comment by Shuyu-XJTU** [comment]
你好。你说的问题确实存在。
如果用BLIP对从监控视频等处收集的图片生成相应描述的话，因为图片的清晰度比较低，很难捕捉到细节信息，所以很难生成较好的文本描述。也就是说，我们尝试过用BLIP对真实行人图像生成描述，效果不好。
在我们的方法中，因为我们生成的图像分辨率还可以，所以可以用BLIP生成相应的描述。
也许可以尝试先将模糊图片进行去模糊处理之后，再生成文本描述。
希望能有帮助。
