### ISSUE TITLE
Issue with Missing JSON Files in gene_attrs Folder after Extracting finetune.zip

### ISSUE THREAD

**Issue by KJW988** [Shuyu-XJTU/APTM#18]
I have organized the files according to "Organize data folder as follows," but when I extracted the finetune.zip file, there were no JSON files inside the gene_attrs folder (such as g_4x_attrs.json). How can I resolve this issue?

**Comment by KJW988** [comment]
I can't access baidu link... Could you provide a Google Drive link?

**Comment by erictan23** [comment]
Hi, I encountered the same problem too, is there a google drive link for gene_attrs folder?

**Comment by KJW988** [comment]
> Hi, I encountered the same problem too, is there a google drive link for gene_attrs folder?

Sorry, I still haven't been able to obtain the Google Drive link for gene_attrs folder.

**Comment by Shuyu-XJTU** [comment]
I have already uploaded it to Google Drive (the same link as finetune.zip).
