### ISSUE TITLE
`c_g_a_9.zip` is not downloadable

### ISSUE THREAD

**Issue by minostauros** [Shuyu-XJTU/APTM#20]
I'm keep failing to download one file `c_g_a_9.zip`

<img width="1095" alt="image" src="https://github.com/Shuyu-XJTU/APTM/assets/6764739/9894850e-3edb-4868-b327-a8ef369e2446">

**Comment by Shuyu-XJTU** [comment]
Sorry, I just saw your message now. Have you resolved the issue yet? If not, please check your internet connection. If that doesn't work, we'll provide a OneDrive link to the dataset within a few days. Hopefully, that will be helpful.
