### ISSUE TITLE
使用pre_trained model进行微调

### ISSUE THREAD

**Issue by laiping-lp** [Shuyu-XJTU/APTM#21]
请问为什么使用pre_trained model在cuhk-pedes这些数据集进行微调时，一直会报out of memory的错误，我的设备如下
![QQ截图20240509112205](https://github.com/Shuyu-XJTU/APTM/assets/72402658/904caf8f-a1f2-4f23-9106-f7f5e8587408)

**Comment by littlexinyi** [comment]
估计是显存不够

**Comment by Shuyu-XJTU** [comment]
可以试着调小batch size
