### ISSUE TITLE
【评估代码的一些疑问】

### ISSUE THREAD

**Issue by chen-si-jia** [Shuyu-XJTU/APTM#22]
1, 请问 评估代码中的 evaluation_attr_only_img_classifier()、evaluation_attr() 和 evaluation()，三种评估函数有什么区别？
2. 请问 evaluation() 评估函数中的 score_matrix_t2i 与 score_sim_t2i 有什么区别？

**Comment by Shuyu-XJTU** [comment]
1、evaluation_attr_only_img_classifier() 和 evaluation_attr()是在PA-100K数据集上的测试代码， 其中evaluation_attr_only_img_classifier()只使用的图片编码器和一个分类器进行测试，主要用于消融实验，而 evaluation_attr()使用了属性文本和图片的对齐模块； evaluation()则是在基于文本的行人检索数据集上的测试代码。
2、score_matrix_t2i 是通过ITM的MLP头计算获得的文本图像匹配分数， score_sim_t2i 是通过ITC部分计算获得的图像文本相似度分数，最终的文本图像匹配排序依据结合了score_matrix_t2i 和 score_sim_t2i

**Comment by wangjl1993** [comment]
> score_sim_t2i

作者你好！关于推理代码，我也有个疑问：按读代码的理解，score（score = model.itm_head(output)[:, 1]），是“ITM的MLP头计算获得的文本图像匹配 属于1（正类）的分数”。不过score_matrix_t2i 却是一批图文数据互相匹配的**相对分数**（有经过Max-Min归一化）。在检索任务评测中，因为图和文都能找到互相对应的对象，这好像没什么问题。

实际我做了一些测试发现：
1. 用公布的ft_cuhk/checkpoint_best.pth模型，测一批15张的图片。模型top1准确率就100%了。不过我看了score发现全部是负数，是否可以这样认为：ITM自身认为所有的图文对都不匹配？ 不过，GroundThruth对应的匹配值是最大的（尽管它也是负数）。相对于其他图像，GroundThruth图像**相对来说是最匹配**的。
![image](https://github.com/Shuyu-XJTU/APTM/assets/8839139/f89ea0ba-79d0-43a9-b9c8-6e0194aeb1bb)
![image](https://github.com/Shuyu-XJTU/APTM/assets/8839139/93f13b2e-e650-4291-a18a-77da72ff42d1)


想请教的事，如果说测试图像只有1对，ITM好像就不能用了？直接取score的话，很多正例都是负数。只能依赖于ITC做比较吗？

**Comment by Shuyu-XJTU** [comment]
“”ITM自身认为所有的图文对都不匹配？” 这个问题我确实没有考虑过，我想是否可以先看看ft_cuhk/checkpoint_best.pth模型在训练集上的测试结果，也就是对应的ITM分数。
测试图像只有1对是指一张文本要去检索一张图片，根据ITM的分数按照某个阈值判断它们是否匹配吗？
期待回复。

**Comment by wangjl1993** [comment]
> “”ITM自身认为所有的图文对都不匹配？” 这个问题我确实没有考虑过，我想是否可以先看看ft_cuhk/checkpoint_best.pth模型在训练集上的测试结果，也就是对应的ITM分数。 测试图像只有1对是指一张文本要去检索一张图片，根据ITM的分数按照某个阈值判断它们是否匹配吗？ 期待回复。

感谢回复！ 

1. **ft_cuhk/checkpoint_best.pth模型在训练集上的测试结果，也就是对应的ITM分数。**没有测试，不过我相信也会有数据会这样，因为模型完全有可能没有完全拟合训练集，这也正常。
2. 我是对采用ITM有疑问，ITM是衡量一句话和一张图的匹配程度，那应该是score = model.itm_head(output).softmax(dim=1)[:, 1]这样吧，这样是分数衡量的是ITM分类头认为**图文为同类的概率**。 而代码中，是score = model.itm_head(output)[:, 1]，之后又对分数矩阵做了Max-Min归一化，如果测试集1为 《description1, img1, img2, img3》（description1, img1是GroundThruth），ce测试集2《description1, img1, img4, img5》，这样两个数据集去测试，两次分数矩阵中（description1- img1）两次的分数是不一样的，因为代码中衡量的是一批数据中相对匹配值，而不是客观匹配值。

**Comment by Shuyu-XJTU** [comment]
是的。因为做了Max-Min归一化，代码中衡量的是一批数据中相对匹配值，而不是客观匹配值。
如果想采用客观值，可以加上softmax，不对矩阵做归一化处理。

**Comment by wangjl1993** [comment]
> 是的。因为做了Max-Min归一化，代码中衡量的是一批数据中相对匹配值，而不是客观匹配值。 如果想采用客观值，可以加上softmax，不对矩阵做归一化处理。

好的，感谢回复，可以关闭问题了。
