### ISSUE TITLE
预训练模型的zero-shot能力

### ISSUE THREAD

**Issue by littlexinyi** [Shuyu-XJTU/APTM#23]
请问该APTM预训练模型直接用于domain generalization下游ReID任务测试的zero-shot能力如何？用于预训练的生成行人数据是否会与下游真实行人数据存在较大的domain gap呢

**Comment by Shuyu-XJTU** [comment]
1、zero-shot能力不太好，这可能与BLIP生成的文本存在相似的风格有关。文本之间风格相似，多样性不够也许会进一步导致预训练模型在文本部分过拟合，在下游数据集上的泛化性能不好。
2、预训练的数据和真实行人数据之间确实存在一定的domain gap。
