### ISSUE TITLE
不同的normlize是怎么得来的

### ISSUE THREAD

**Issue by abueidvchow** [Shuyu-XJTU/APTM#25]
我注意到你们用在CUHK，ICFG和RSTP上的normlize是不一样的，这些不同的normlize是怎么得来的？
![图片](https://github.com/Shuyu-XJTU/APTM/assets/55395215/64557d43-7eda-4bd0-8b8e-69681f7bbf4c)

**Comment by Shuyu-XJTU** [comment]
通过计算不同数据集中图片的均值和方差得到的
