### ISSUE TITLE
多数据集混合微调训练

### ISSUE THREAD

**Issue by wangjl1993** [Shuyu-XJTU/APTM#26]
作者你好！如果把不同数据集混合微调，比如cuhk+icfg，需要做以下工作：
1. 把icfg的caption离线处理成cuhk格式（全部小写，标点符号替换为空格。）
2. icfg数据集的image_id累加cuhk的最大id
3. （需要计算新的均值方差吗）

除此之外还需要其他修改吗？这样多数据集的微调模型泛华效果是否会更好呢？期待回复，谢谢！

**Comment by Shuyu-XJTU** [comment]
你好！均值方差的影响可能不会很大，但可以试试。
除此之外应该没有什么需要修改的。
我认为多数据集的微调模型泛华效果会更好，但没有具体试过，期待你的尝试结果。

**Comment by wangjl1993** [comment]
> 回复

你好，我做了一些尝试，如下：
1. cuhk+icfg，均值方差用的是cuhk数据集的，微调30epo后，和ft_cuhk.pth的模型相比，在cuhk的测试集上没有什么提升，基本持平。筛选了UFine数据集](https://github.com/Zplusdragon/UFineBench), (仅保留来自UFine数据源的数据，且描述词在60个以下。)作为一个新的测试集，cuhk+icfg.pth比ft_cuhk.pth略好一丢丢，top1持平，top5提升2个点。
2. cuhk+icfg+iiitd-20k[https://github.com/Visual-Conception-Group/Dense-Captioning-for-Text-Image-ReID](url)微调，设置和上面一样，但是Ufine测试集效果变差了很多= =..（top1掉了10个点），该模型微调过程中，在cuhk的测试上表现还是正常的，所以才来提问。。。不知道是哪里出了问题

**Comment by Shuyu-XJTU** [comment]
可能还是因为数据集之间的domain gap，或许可以想办法消除这种gap，关注数据之间共性的特征，提高泛化性。
