### ISSUE TITLE
数据集的json文件处理步骤

### ISSUE THREAD

**Issue by CZYdeGithub** [Shuyu-XJTU/APTM#27]
想问一下json文件预处理做了哪些步骤？对自己的数据集运行出现了以下错误
![Uploading 捕获.PNG…]()

**Comment by layumi** [comment]
你好 @CZYdeGithub  
你的png 没有上传成功？能否再贴一下。

**Comment by CZYdeGithub** [comment]
图片没找到了，只是一个读取的报错（但他发生在开始读批次之后中间批次报错）。我想弄清楚是不是我json处理的问题，看代码里好像没有对于json预处理代码，所以想请问对原json文件进行了那些处理步骤，谢谢。

**Comment by Shuyu-XJTU** [comment]
你好。实验没有对json文件进行额外的处理，而是直接读取json文件。后续对读取到的图片和文本进行了一些预处理。

**Comment by CZYdeGithub** [comment]
好的，感谢回复。
