### ISSUE TITLE
关于mlm的一些疑问

### ISSUE THREAD

**Issue by clarkhedi** [Shuyu-XJTU/APTM#29]
您好！感谢您的开源代码。
对于mlm代码，我有一点疑惑，如下图所示，最后返回的是原始的text_ids_masked，所以在进行MLM时，与图像交互的文本token是没有进行mask嘛？非常感谢您的回复！

![image](https://github.com/user-attachments/assets/c5bb5737-09e4-4966-aa1e-202bbdf5c388)

**Comment by Shuyu-XJTU** [comment]
你好。在class TextMaskingGenerator中有mask_generator(text_id)这一步具体完成的工作，在这一步中，text_ids_masked已经改变。可以试试直接打印text_ids_masked的值验证一下。
