### ISSUE TITLE
APL 损失设置

### ISSUE THREAD

**Issue by Yaozl2018** [Shuyu-XJTU/APTM#3]
作者您好，
    非常感谢贵团队带来的杰出工作APTM。我在尝试基于APTM框架和MALS数据集进行预训练时，发现你们提供的默认配置文件Retrieval_gene.yaml当中将APL损失以及其对应的权重β注释掉了，即配置文件中的attr、t两个变量，也就是说你们默认的配置文件未开启APL损失的计算。目前训练下来发现：
    （1）按照你们的默认配置文件（不开启APL损失计算）是能够正常训练的，但预训练的结果无法与你们对比，因为你们提供的预训练模型权重文件的共享链接失效了，无法测试你们aptm框架基于MALS数据集进行预训练的性能。请问你们后续是否能够更新一下模型权重文件的共享链接，非常感谢。
    （2）若按照你们论文中的设置，将默认配置文件的APL损失开启，模型无法正常训练，apl损失值出现了nan现象，请问apl损失的计算是需要什么其他的设置遗漏了吗，或者我使用的方式有什么需要修改吗，目前是完全按照你们的代码和github上的配置文件进行复现的。或者说，出现nan现象，对于aptm框架来说是正常的吗？

非常感谢抽空阅读这个issue。

**Comment by Shuyu-XJTU** [comment]
您好，感谢您的问题。

（1）我们重新检查了预训练模型权重文件的共享链接，应该是没有失效的。

（2）正常的训练是不会出现nan现象的，也许是配置文件的问题，配置文件应该加上LabelSmooth的设置。

attr: True LabelSmooth: 0.4t: 0.8
不知道我的回答能否解决您的问题，如果还有其他问题，欢迎讨论。

-----原始邮件-----
发件人:Yaozl2018 ***@***.***>
发送时间:2023-08-15 10:09:11 (星期二)
收件人: Shuyu-XJTU/APTM ***@***.***>
抄送: Subscribed ***@***.***>
主题: [Shuyu-XJTU/APTM] APL 损失设置 (Issue #3)






作者您好，
非常感谢贵团队带来的杰出工作APTM。我在尝试基于APTM框架和MALS数据集进行预训练时，发现你们提供的默认配置文件Retrieval_gene.yaml当中将APL损失以及其对应的权重β注释掉了，即配置文件中的attr、t两个变量，也就是说你们默认的配置文件未开启APL损失的计算。目前训练下来发现：
（1）按照你们的默认配置文件（不开启APL损失计算）是能够正常训练的，但预训练的结果无法与你们对比，因为你们提供的预训练模型权重文件的共享链接失效了，无法测试你们aptm框架基于MALS数据集进行预训练的性能。请问你们后续是否能够更新一下模型权重文件的共享链接，非常感谢。
（2）若按照你们论文中的设置，将默认配置文件的APL损失开启，模型无法正常训练，apl损失值出现了nan现象，请问apl损失的计算是需要什么其他的设置遗漏了吗，或者我使用的方式有什么需要修改吗，目前是完全按照你们的代码和github上的配置文件进行复现的。或者说，出现nan现象，对于aptm框架来说是正常的吗？

非常感谢抽空阅读这个issue。

**Comment by Yaozl2018** [comment]
谢谢恢复，目前问题1、2均已解决。

此外，还有一个疑惑想要请教一下。我在论文中看到你们将image_encoder的patch size设置成32，但在阅读代码中发现models/aptm.py 的第85行却是将patch size写成了固定值4。请问造成这个差异的原因是什么呢？

非常感谢抽空阅读这个issue。

**Comment by Shuyu-XJTU** [comment]
谢谢您的问题。
代码中Swin-B的patch size是4，这意味着Swin-B先将图像分割成每块大小为 4 x 4 的patch, 得到初始resolution，也就是模型后面每个stage会降采样的维度。如果输入图片的尺寸是 384 x 128 ，初始 resolution 就是 96 x 32，经过后面的几次降采样，在最后的平均池化之前，模型得到384/32 x 128/32 = 12 x 4 个tokens， 这个32就是论文中“将image_encoder的patch size设置成32”的32。
