### ISSUE TITLE
请教一下属性标注的具体做法

### ISSUE THREAD

**Issue by barry-wy** [Shuyu-XJTU/APTM#31]
文章中提到的两个机制：Explicit Matching和Implicit Extension。具体是如何实现的？是仅通过文本中查找关键词实现的嘛？能否提供关键词列表？

**Comment by Shuyu-XJTU** [comment]
你好。很抱歉，间隔这么久才回复。
两个机制都通过查找句子中的关键词进行标注。
Explicit Matching：通过明显指示性的单词确定属性，例如通过man,woman等确定性别。
Implicit Extension：通过一些单词或短语推理属性，例如通过little baby这种短语确定年龄。
具体实现的原始代码cuhk_attribute.py已经上传到分享checkpoint的百度网盘链接里，代码没有进一步整理，还请见谅。

**Comment by jesanli** [comment]
> 文章中提到的两个机制：Explicit Matching和Implicit Extension。具体是如何实现的？是仅通过文本中查找关键词实现的嘛？能否提供关键词列表？

您有获得代码嘛，具体是怎么实现的，能提供嘛？

**Comment by Shuyu-XJTU** [comment]
你好，这是新的链接：
通过网盘分享的文件：cuhk_attribute.py
链接: https://pan.baidu.com/s/1SHiDedg8yKiqMm5cfns1ZA?pwd=ndfr 提取码: ndfr 
--来自百度网盘超级会员v6的分享

**Comment by jesanli** [comment]
Thank you for your prompt reply！
