### ISSUE TITLE
大佬们，我想知道文本编码器使用bert前六层和交叉编码器使用的bert后六层在代码中哪里体现

### ISSUE THREAD

**Issue by newbie521** [Shuyu-XJTU/APTM#7]

**Comment by Shuyu-XJTU** [comment]
您好。可以看看models/aptm.py 的 get_text_embeds() 和 get_cross_embeds() 两个方法的区别，具体实现的代码在 bert.py 类BertEncoder() 的 forward() 方法中。

**Comment by newbie521** [comment]
> 您好。可以看看models/aptm.py 的 get_text_embeds() 和 get_cross_embeds() 两个方法的区别，具体实现的代码在 bert.py 类BertEncoder() 的 forward() 方法中。

感谢您的回复，我知道了他们之间的关系了！
