### ISSUE TITLE
gene_crop/c_g_a_1/文件夹下有多个图像缺失

### ISSUE THREAD

**Issue by DuGuodong111** [Shuyu-XJTU/APTM#8]
您好，非常感谢您能够开源代码和数据集！在我预训练的过程中，我发现gene_crop/c_g_a_1/路径下，缺失了多个图像。是不是您上传json的时候，上传了未整理的版本呢？

**Comment by Shuyu-XJTU** [comment]
您好。我应该上传的是整理过的版本，可以描述一下具体是缺失了那些图片吗？

**Comment by DuGuodong111** [comment]
gene_crop/c_g_a_1/9567.jpg,
gene_crop/c_g_a_1/13702.jpg,
gene_crop/c_g_a_1/5390.jpg,
gene_crop/c_g_a_1/4519.jpg,
gene_crop/c_g_a_1/13412.jpg,
gene_crop/c_g_a_1/808.jpg,
gene_crop/c_g_a_1/15214.jpg,
gene_crop/c_g_a_1/12208.jpg,
gene_crop/c_g_a_1/9567.jpg,
目前只训练了第一个epoch，发现缺失了这些图像，并且第一个epoch的测试阶段缺失了CUHK-PEODS/train_query/p8848_s17661.jpg

**Comment by DuGuodong111** [comment]
抱歉，test阶段的图像是由于路径原因导致的，图像本身没有缺失，但是train阶段确实没有相应的图像

**Comment by Shuyu-XJTU** [comment]
您好，请您尝试重新解压相应的图片文件夹压缩包。我重新检查了数据集，这些缺失图片应该在压缩包中。

-----原始邮件-----
发件人:DuGuodong111 ***@***.***>
发送时间:2023-09-22 09:10:59 (星期五)
收件人: Shuyu-XJTU/APTM ***@***.***>
抄送: Shuyu-XJTU ***@***.***>, Comment ***@***.***>
主题: Re: [Shuyu-XJTU/APTM] gene_crop/c_g_a_1/文件夹下有多个图像缺失 (Issue #8)






抱歉，test阶段的图像是由于路径原因导致的，图像本身没有缺失，但是train阶段确实没有相应的图像
